In [1]:
print('hello')

hello


# pandas and numpy


In [27]:
 import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
a.ndim

1

In [5]:
a = np.array([[[[1,2,3,6],[4,5,6,5],[4,5,6,5]]]])
print(a)
a.ndim
a.shape
a.size
a.itemsize

[[[[1 2 3 6]
   [4 5 6 5]
   [4 5 6 5]]]]


4

In [6]:
#a[:,2]
#a[0,2]=600

In [7]:
np.zeros((3,3),dtype="int64")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [8]:
x=np.ones((3,3))
x
x.dtype

dtype('float64')

In [9]:
np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [10]:
np.full_like(x,3)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [11]:
np.random.randint(5,10,size=(3,3))

array([[8, 7, 6],
       [6, 6, 7],
       [7, 9, 9]])

In [12]:
a= np.array([1,2,3,4,5])
b= np.array([10,20,30,40,50])

In [13]:
a+10

array([11, 12, 13, 14, 15])

In [14]:
a+b

array([11, 22, 33, 44, 55])

In [15]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [16]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [17]:
np.matmul(a,b)

550

In [18]:
  df = pd.DataFrame({"Names":["xyz","hgy","jki","uiu"],
                    "College":["pes","pes","pes","kle"],
                    "Address":["gdg","smg","kpl","dwd"]})
df

Names College Address
0   xyz     pes     gdg
1   hgy     pes     smg
2   jki     pes     kpl
3   uiu     kle     dwd

In [19]:
df.head()    #will print first 5 rows

Names College Address
0   xyz     pes     gdg
1   hgy     pes     smg
2   jki     pes     kpl
3   uiu     kle     dwd

In [20]:
df.tail()    #last 5 rows

Names College Address
0   xyz     pes     gdg
1   hgy     pes     smg
2   jki     pes     kpl
3   uiu     kle     dwd

In [21]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Names    4 non-null      object
 1   College  4 non-null      object
 2   Address  4 non-null      object
dtypes: object(3)
memory usage: 224.0+ bytes


In [22]:
df.describe()

Names College Address
count      4       4       4
unique     4       2       4
top      uiu     pes     gdg
freq       1       3       1

#df = pd.read_csv("supermarket.csv")       txt, pdf, doc, excell: csv, xlsx, xls

In [23]:
sampledf = pd.read_csv("sample.csv")

In [24]:
sampledf

Series_reference   Period  Data_value Suppressed STATUS    UNITS  \
0       BDCQ.SF1AA2CA  2016.06    1116.386        NaN      F  Dollars   
1       BDCQ.SF1AA2CA  2016.09    1070.874        NaN      F  Dollars   
2       BDCQ.SF1AA2CA  2016.12    1054.408        NaN      F  Dollars   
3       BDCQ.SF1AA2CA  2017.03    1010.665        NaN      F  Dollars   
4       BDCQ.SF1AA2CA  2017.06    1233.700        NaN      F  Dollars   
...               ...      ...         ...        ...    ...      ...   
3055    BDCQ.SF8RS2CA  2020.03     141.986        NaN      F  Dollars   
3056    BDCQ.SF8RS2CA  2020.06      -5.260        NaN      F  Dollars   
3057    BDCQ.SF8RS2CA  2020.09      73.572        NaN      F  Dollars   
3058    BDCQ.SF8RS2CA  2020.12     229.689        NaN      F  Dollars   
3059    BDCQ.SF8RS2CA  2021.03     155.167        NaN      F  Dollars   

      Magnitude                         Subject  \
0             6  Business Data Collection - BDC   
1             6  Business Data Collection - BDC   
2             6  Business Data Collection - BDC   
3             6  Business Data Collection - BDC   
4             6  Business Data Collection - BDC   
...         ...                             ...   
3055          6  Business Data Collection - BDC   
3056          6  Business Data Collection - BDC   
3057          6  Business Data Collection - BDC   
3058          6  Business Data Collection - BDC   
3059          6  Business Data Collection - BDC   

                               Group            Series_title_1  \
0     Industry by financial variable  Sales (operating income)   
1     Industry by financial variable  Sales (operating income)   
2     Industry by financial variable  Sales (operating income)   
3     Industry by financial variable  Sales (operating income)   
4     Industry by financial variable  Sales (operating income)   
...                              ...                       ...   
3055  Industry by financial variable          Operating profit   
3056  Industry by financial variable          Operating profit   
3057  Industry by financial variable          Operating profit   
3058  Industry by financial variable          Operating profit   
3059  Industry by financial variable          Operating profit   

            Series_title_2  Series_title_3 Series_title_4  Series_title_5  
0     Forestry and Logging  Current prices     Unadjusted             NaN  
1     Forestry and Logging  Current prices     Unadjusted             NaN  
2     Forestry and Logging  Current prices     Unadjusted             NaN  
3     Forestry and Logging  Current prices     Unadjusted             NaN  
4     Forestry and Logging  Current prices     Unadjusted             NaN  
...                    ...             ...            ...             ...  
3055        Other Services  Current prices     Unadjusted             NaN  
3056        Other Services  Current prices     Unadjusted             NaN  
3057        Other Services  Current prices     Unadjusted             NaN  
3058        Other Services  Current prices     Unadjusted             NaN  
3059        Other Services  Current prices     Unadjusted             NaN  

[3060 rows x 14 columns]

In [25]:
sampledf.isnull().sum()

Series_reference       0
Period                 0
Data_value           242
Suppressed          2818
STATUS                 0
UNITS                  0
Magnitude              0
Subject                0
Group                  0
Series_title_1         0
Series_title_2         0
Series_title_3         0
Series_title_4         0
Series_title_5      3060
dtype: int64