In [1]:
 import numpy as np

In [2]:
a = np.array([[1,2,3],[5,6,7]], dtype='float')
b = np.array((1,3,2))

In [3]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
d = np.full((3,3),6, dtype ='complex')
d

array([[6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j]])

In [5]:
e= np.random.random((2,3))
e

array([[0.71110426, 0.27267129, 0.38528069],
       [0.38864472, 0.3869379 , 0.83201831]])

In [6]:
f = np.linspace(0, 5, 10)
f

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [7]:
array = np.array([[1,2,3,4],[5,6,7,8],[1,2,0,8]])
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 0, 8]])

In [8]:
newarr = array.reshape(2,2,3)
newarr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 1],
        [2, 0, 8]]])

In [9]:
arr = np.array([[1,2,3],[5,6,7]])
flarr = arr.flatten()

In [10]:
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [11]:
flarr

array([1, 2, 3, 5, 6, 7])

In [12]:
 array.T    # transpose(of above array)

array([[1, 5, 1],
       [2, 6, 2],
       [3, 7, 0],
       [4, 8, 8]])

In [13]:
print('largest of all elemaent:',array.max())

largest of all elemaent: 8


In [14]:
print('largest of row-wise of all elemaent:',array.max(axis = 0 ))

largest of row-wise of all elemaent: [5 6 7 8]


In [15]:
print('smallest of row-wise of all elemaent:',array.min(axis = 1))

smallest of row-wise of all elemaent: [1 5 0]


In [16]:
print('sum of all array :',array.sum())

sum of all array : 47


In [17]:
a+b


array([[2., 5., 5.],
       [6., 9., 9.]])

In [18]:
a+1

array([[2., 3., 4.],
       [6., 7., 8.]])

In [19]:
a-2

array([[-1.,  0.,  1.],
       [ 3.,  4.,  5.]])

In [20]:
a*2

array([[ 2.,  4.,  6.],
       [10., 12., 14.]])

In [21]:
a**2

array([[ 1.,  4.,  9.],
       [25., 36., 49.]])

In [22]:
  np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131]])

In [23]:
p = np.array([[1,4,2],[3,4,6],[0,-1,5]])
p

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

In [24]:
print('sorting:',np.sort(p, axis = None))

sorting: [-1  0  1  2  3  4  4  5  6]


In [25]:
print('row-sorting:',np.sort(p, axis = 1))

row-sorting: [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [26]:
print('column-sorting:',np.sort(p, axis =0))

column-sorting: [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


#  sliceing

In [27]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[5,8,9,2,7]])
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 5,  8,  9,  2,  7]])

In [28]:
print(A[0:2, 2])

[3 8]


In [29]:
print(A[0:1,2:4])

[[3 4]]


In [30]:
print(A[:2,1:4])

[[2 3 4]
 [7 8 9]]


In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
a= np.array([1,2,4])

In [34]:
b=np.array([6,5,8])

In [35]:
np.hstack([a,b])

array([1, 2, 4, 6, 5, 8])

In [36]:
np.vstack([b,a])

array([[6, 5, 8],
       [1, 2, 4]])